
import { Question } from './types';

const mapGabarito: Record<string, number> = { "A": 0, "B": 1, "C": 2, "D": 3 };

const mapJsonToQuestions = (json: any[]): Question[] => {
  return json.map(q => ({
    id: q.id.toString(),
    ciclo: q.ciclo,
    modalidade: q.modalidade === "Tradicional" ? "Morfofuncional" : "PBL",
    modulo: q.modulo,
    tema: q.tema,
    problema: q.problema,
    enunciado: q.enunciado,
    alternativas: [
      q.alternativas.A,
      q.alternativas.B,
      q.alternativas.C,
      q.alternativas.D
    ],
    gabarito: mapGabarito[q.gabarito] ?? 0
  }));
};

// --- NOVAS 50 QUESTÕES MÓDULO 7 ---
const NEW_M7_QUESTIONS_RAW = [
  { id: 501, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Neuroendocrinologia", problema: 1, enunciado: "No circuito dos neurônios KNDy, qual é a função específica da Dinorfina na regulação da pulsatilidade do GnRH?", alternativas: { A: "Iniciar o pulso secretório", B: "Sincronizar os neurônios via Neurocinina B", C: "Encerrar o pulso via feedback inibitório (freio)", D: "Estimular diretamente a hipófise" }, gabarito: "C" },
  { id: 502, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Ciclo Menstrual", problema: 1, enunciado: "Qual evento molecular marca o início da luteólise e a consequente menstruação na ausência de gravidez?", alternativas: { A: "Aumento da Inibina B", B: "Queda nos níveis de LH levando ao colapso do corpo lúteo", C: "Pico de Estradiol", D: "Ação da Prolactina" }, gabarito: "B" },
  { id: 503, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Contracepção", problema: 1, enunciado: "Qual categoria de métodos contraceptivos apresenta a maior discrepância entre a eficácia no 'Uso Perfeito' e no 'Uso Típico'?", alternativas: { A: "LARC (DIU e Implante)", B: "Esterilização Cirúrgica", C: "Métodos Comportamentais e de Barreira", D: "Contraceptivos Injetáveis" }, gabarito: "C" },
  { id: 504, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Patologia Ovariana", problema: 1, enunciado: "Na fisiopatologia da SOP, qual alteração no padrão de pulso do GnRH é observada e qual sua consequência?", alternativas: { A: "Pulsatilidade lenta, aumentando FSH", B: "Pulsatilidade rápida, favorecendo secreção de LH e hiperandrogenismo", C: "Ausência de pulsatilidade", D: "Pulsatilidade caótica sem efeito hormonal" }, gabarito: "B" },
  { id: 505, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Infectologia", problema: 1, enunciado: "Qual manifestação clínica distingue classicamente a Sífilis Primária da Secundária?", alternativas: { A: "Cancro duro (local) vs. Roséola/Sintomas Sistêmicos", B: "Goma sifilítica vs. Cancro mole", C: "Assintomática vs. Neurossífilis", D: "Úlcera dolorosa vs. Úlcera indolor" }, gabarito: "A" },
  { id: 506, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Infectologia", problema: 1, enunciado: "O que permite aos testes de HIV de 4ª geração reduzirem a janela imunológica para cerca de 15 a 30 dias?", alternativas: { A: "Detecção exclusiva de IgM", B: "Detecção simultânea de anticorpos e do antígeno p24", C: "Uso de PCR em tempo real", D: "Alta sensibilidade para carga viral" }, gabarito: "B" },
  { id: 507, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Oncologia Preventiva", problema: 1, enunciado: "Quais genótipos de HPV são classificados como de 'Alto Risco' oncogênico e são os principais alvos das vacinas?", alternativas: { A: "6 e 11", B: "16 e 18", C: "31 e 33", D: "40 e 42" }, gabarito: "B" },
  { id: 508, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Fisiologia do Esporte", problema: 1, enunciado: "Qual o mecanismo central da amenorreia na Tríade da Mulher Atleta?", alternativas: { A: "Falência ovariana prematura", B: "Supressão hipotalâmica do GnRH devido à baixa disponibilidade energética", C: "Excesso de conversão periférica de estrogênio", D: "Hiperprolactinemia por exercício" }, gabarito: "B" },
  { id: 509, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Contracepção", problema: 1, enunciado: "Qual o principal mecanismo de ação das minipílulas de progestágeno isolado?", alternativas: { A: "Anovulação em 100% dos ciclos", B: "Espessamento do muco cervical (hostilidade ao espermatozoide)", C: "Luteólise precoce", D: "Bloqueio tubário físico" }, gabarito: "B" },
  { id: 510, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Saúde Pública", problema: 1, enunciado: "Como fatores estruturais impactam o manejo das ISTs em populações vulneráveis?", alternativas: { A: "Aumentam a virulência bacteriana", B: "Criam barreiras de acesso e diagnóstico devido ao estigma", C: "Reduzem a eficácia farmacológica dos antibióticos", D: "Eliminam a necessidade de rastreio" }, gabarito: "B" },
  { id: 511, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Meiose", problema: 2, enunciado: "O que mantém o ovócito primário estacionado na Prófase I (Diplóteno)?", alternativas: { A: "Altos níveis de LH", B: "Níveis elevados de AMPc mantidos pelo OMI (Oocyte Maturation Inhibitor)", C: "Ausência de mitocôndrias", D: "Degradação das coesinas" }, gabarito: "B" },
  { id: 512, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Espermatogênese", problema: 2, enunciado: "Durante a espermiogênese, as histonas são substituídas por quais proteínas para compactar o DNA?", alternativas: { A: "Albuminas", B: "Protaminas", C: "Globulinas", D: "Queratinas" }, gabarito: "B" },
  { id: 513, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Fecundação", problema: 2, enunciado: "Quais proteínas formam o par chave-fechadura essencial para a fusão dos gametas?", alternativas: { A: "ZP3 e ZP2", B: "Izumo1 (espermatozoide) e Juno (ovócito)", C: "Acrosina e Hialuronidase", D: "Integrinas e Selectinas" }, gabarito: "B" },
  { id: 514, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Fecundação", problema: 2, enunciado: "O que caracteriza a 'Reação Cortical' (bloqueio lento)?", alternativas: { A: "Influxo de Sódio", B: "Liberação de grânulos que endurecem a Zona Pelúcida (clivagem de ZP2)", C: "Morte dos espermatozoides restantes", D: "Fechamento da tuba uterina" }, gabarito: "B" },
  { id: 515, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Genética", problema: 2, enunciado: "Qual o mecanismo básico do Imprinting Genômico?", alternativas: { A: "Mutação de sequência", B: "Silenciamento gênico dependente da origem parental (metilação)", C: "Deleção cromossômica total", D: "Herança mitocondrial" }, gabarito: "B" },
  { id: 516, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Epigenética", problema: 2, enunciado: "O que ocorre com as marcas epigenéticas nas Células Germinativas Primordiais durante a migração?", alternativas: { A: "São duplicadas", B: "Sofrem 'erasure' (apagamento) para serem reestabelecidas conforme o sexo do embrião", C: "Tornam-se permanentes", D: "São transferidas para as células somáticas" }, gabarito: "B" },
  { id: 517, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Anatomia Microscópica", problema: 2, enunciado: "Qual a principal função da barreira hematotesticular formada pelas células de Sertoli?", alternativas: { A: "Nutrir células de Leydig", B: "Proteger células germinativas haploides (antigênicas) do sistema imune", C: "Produzir testosterona", D: "Filtrar o plasma seminal" }, gabarito: "B" },
  { id: 518, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Biologia Celular", problema: 2, enunciado: "Qual íon é responsável pelas oscilações intracelulares que reativam a meiose após a entrada do espermatozoide?", alternativas: { A: "Sódio", B: "Potássio", C: "Cálcio", D: "Magnésio" }, gabarito: "C" },
  { id: 519, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Genética Clínica", problema: 2, enunciado: "Por que a idade materna avançada aumenta o risco de trissomias?", alternativas: { A: "Menor vascularização uterina", B: "Degradação das coesinas cromossômicas durante a longa parada na Prófase I", C: "Falta de hormônios", D: "Mutação no DNA mitocondrial" }, gabarito: "B" },
  { id: 520, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Fatores Ambientais", problema: 2, enunciado: "Qual o efeito do estresse térmico nos testículos?", alternativas: { A: "Acelera a meiose", B: "Induz apoptose celular e reduz contagem de espermatozoides", C: "Aumenta a produção de testosterona", D: "Melhora a motilidade" }, gabarito: "B" },
  { id: 521, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Pré-Natal", problema: 3, enunciado: "Qual a justificativa clínica para consultas semanais no final do terceiro trimestre?", alternativas: { A: "Apoio psicológico", B: "Vigilância de pré-eclâmpsia e insuficiência placentária", C: "Indução de parto", D: "Burocracia hospitalar" }, gabarito: "B" },
  { id: 522, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Semiologia", problema: 3, enunciado: "Uma altura uterina acima do percentil 90 sugere quais diagnósticos?", alternativas: { A: "Oligoidrâmnio e CIUR", B: "Polidrâmnio, macrossomia ou gemelaridade", C: "Morte fetal", D: "Erro de datação para menos" }, gabarito: "B" },
  { id: 523, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Nutrição na Gestação", problema: 3, enunciado: "Qual a recomendação de cálcio para prevenção de pré-eclâmpsia em populações de risco?", alternativas: { A: "Não é recomendado", B: "500mg/dia", C: "1.000 a 2.000 mg/dia (longe do ferro)", D: "Apenas via dieta" }, gabarito: "C" },
  { id: 524, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Infectologia Obstétrica", problema: 3, enunciado: "Para ser considerado adequado, o tratamento da sífilis materna deve ser finalizado quanto tempo antes do parto?", alternativas: { A: "7 dias", B: "15 dias", C: "30 dias", D: "Qualquer momento antes do parto" }, gabarito: "C" },
  { id: 525, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Imunização", problema: 3, enunciado: "Qual o objetivo principal da dTpa após a 20ª semana?", alternativas: { A: "Proteger a mãe do tétano", B: "Transferir anticorpos contra Coqueluche para o feto", C: "Prevenir difteria materna", D: "Substituir a vacina de Hepatite B" }, gabarito: "B" },
  { id: 526, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Endocrinologia Obstétrica", problema: 3, enunciado: "Uma glicemia de jejum de 94 mg/dL na primeira consulta de pré-natal indica:", alternativas: { A: "Normalidade", B: "Necessidade de TOTG imediato", C: "Diagnóstico de Diabetes Gestacional", D: "Diabetes Prévio (Overt)" }, gabarito: "C" },
  { id: 527, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Urgências", problema: 3, enunciado: "Quais são os componentes da Síndrome HELLP?", alternativas: { A: "Hipertensão e Edema", B: "Hemólise, Enzimas Hepáticas Elevadas, Plaquetopenia", C: "Hemorragia e Infecção", D: "Dor epigástrica e Cefaleia" }, gabarito: "B" },
  { id: 528, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Propedêutica Fetal", problema: 3, enunciado: "Qual a janela ideal para o ultrassom morfológico de segundo trimestre?", alternativas: { A: "11-14 semanas", B: "20-24 semanas", C: "28-32 semanas", D: "36-38 semanas" }, gabarito: "B" },
  { id: 529, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Saúde do Homem", problema: 3, enunciado: "Qual a importância clínica de tratar o parceiro nas ISTs?", alternativas: { A: "Apenas estatística", B: "Evitar reinfecção da gestante", C: "Garantir licença paternidade", D: "Cumprir burocracia" }, gabarito: "B" },
  { id: 530, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Alto Risco", problema: 3, enunciado: "Como é classificada a gestante com 3 abortos consecutivos?", alternativas: { A: "Baixo Risco", B: "Risco Habitual", C: "Alto Risco", D: "Risco Intermediário" }, gabarito: "C" },
  { id: 531, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Estática Fetal", problema: 4, enunciado: "Qual o diâmetro de apresentação na flexão total (vértice)?", alternativas: { A: "Occipitofrontal", B: "Suboccipitobregmático (9,5 cm)", C: "Mentoniano", D: "Biparietal" }, gabarito: "B" },
  { id: 532, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Mecanismo de Parto", problema: 4, enunciado: "Por que a variedade Occipito-Posterior (OP) prolonga o parto?", alternativas: { A: "Feto maior", B: "Necessidade de rotação de 135 graus (grande rotação)", C: "Falta de contração", D: "Colo não dilata" }, gabarito: "B" },
  { id: 533, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Distocias", problema: 4, enunciado: "Por que a apresentação de Fronte é geralmente indicação de cesárea?", alternativas: { A: "Apresenta o diâmetro mentoniano (13,5cm), incompatível com a bacia", B: "Risco de prolapso de braço", C: "Ausência de dilatação", D: "Sofrimento fetal imediato" }, gabarito: "A" },
  { id: 534, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Avaliação de Descida", problema: 4, enunciado: "O que define o Plano Zero de De Lee?", alternativas: { A: "Cabeça móvel", B: "Cabeça nas espinhas isquiáticas (insinuada)", C: "Cabeça na vulva", D: "Cabeça no estreito superior" }, gabarito: "B" },
  { id: 535, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Situação Fetal", problema: 4, enunciado: "Qual o maior risco na rotura de membranas em situação transversa?", alternativas: { A: "Prolapso de cordão", B: "Embolia amniótica", C: "Descolamento de placenta", D: "Parada de contrações" }, gabarito: "A" },
  { id: 536, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Anatomia Pélvica", problema: 4, enunciado: "Qual tipo de bacia tem o diâmetro anteroposterior maior que o transverso?", alternativas: { A: "Ginecoide", B: "Androide", C: "Antropoide", D: "Platipeloide" }, gabarito: "C" },
  { id: 537, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Tempos do Parto", problema: 4, enunciado: "O que é o movimento de Restituição?", alternativas: { A: "Giro interno da cabeça", B: "Giro externo da cabeça para alinhar com os ombros", C: "Saída da placenta", D: "Flexão do pescoço" }, gabarito: "B" },
  { id: 538, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Distocias", problema: 4, enunciado: "No Assinclitismo Posterior (Litzmann), qual osso parietal desce primeiro?", alternativas: { A: "Anterior", B: "Posterior", C: "Ambos iguais", D: "Frontal" }, gabarito: "B" },
  { id: 539, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Nomenclatura", problema: 4, enunciado: "O que significa 'E' na sigla OEA?", alternativas: { A: "Esquerda da mãe", B: "Estendida", C: "Estreito inferior", D: "Espinha ciática" }, gabarito: "A" },
  { id: 540, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Parto Pélvico", problema: 4, enunciado: "Qual o principal risco mecânico do parto pélvico?", alternativas: { A: "Cabeça derradeira (retenção da cabeça)", B: "Distocia de ombro", C: "Inversão uterina", D: "Hemorragia pós-parto" }, gabarito: "A" },
  { id: 541, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Lactação", problema: 5, enunciado: "O que desencadeia a Lactogênese II (Apojadura)?", alternativas: { A: "Sucção do bebê", B: "Queda da Progesterona placentária", C: "Aumento da ocitocina", D: "Ingestão de água" }, gabarito: "B" },
  { id: 542, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Fisiologia da Lactação", problema: 5, enunciado: "Como atua o FIL (Feedback Inhibitor of Lactation)?", alternativas: { A: "Estimula a produção", B: "Inibe a produção localmente quando o alvéolo está cheio", C: "Atua no hipotálamo", D: "Aumenta a gordura do leite" }, gabarito: "B" },
  { id: 543, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Neonatologia", problema: 5, enunciado: "Qual o papel das catecolaminas do parto na respiração neonatal?", alternativas: { A: "Relaxar músculos", B: "Estimular reabsorção do líquido pulmonar via canais de sódio", C: "Fechar o forame oval", D: "Produzir surfactante no fígado" }, gabarito: "B" },
  { id: 544, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Circulação Fetal", problema: 5, enunciado: "O que mantém o Canal Arterial aberto na vida fetal?", alternativas: { A: "Alto oxigênio", B: "Prostaglandina E2 e baixo oxigênio", C: "Insulina", D: "Pressão arterial alta" }, gabarito: "B" },
  { id: 545, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Termorregulação", problema: 5, enunciado: "Qual o principal mecanismo de produção de calor do recém-nascido?", alternativas: { A: "Tremores musculares", B: "Termogênese química na gordura marrom", C: "Vasodilatação", D: "Exercício físico" }, gabarito: "B" },
  { id: 546, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Puerpério Clínico", problema: 5, enunciado: "Onde se palpa o fundo uterino logo após a dequitação da placenta?", alternativas: { A: "Sínfise púbica", B: "Cicatriz umbilical", C: "Apêndice xifoide", D: "Fossa ilíaca" }, gabarito: "B" },
  { id: 547, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Puerpério Patológico", problema: 5, enunciado: "A persistência de lóquios rubros (vermelhos) após 2 semanas sugere:", alternativas: { A: "Normalidade", B: "Subinvolução uterina ou restos placentários", C: "Retorno da menstruação", D: "Cicatrização rápida" }, gabarito: "B" },
  { id: 548, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Saúde Mental", problema: 5, enunciado: "Qual a diferença entre Blues Puerperal e Depressão Pós-Parto?", alternativas: { A: "Blues é autolimitado e leve; Depressão é persistente e incapacitante", B: "Blues exige medicação", C: "Depressão tem alucinações sempre", D: "São sinônimos" }, gabarito: "A" },
  { id: 549, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Triagem Neonatal", problema: 5, enunciado: "O que o teste de oximetria de pulso (coraçãozinho) visa detectar?", alternativas: { A: "Sopros", B: "Cardiopatias críticas dependentes do canal arterial", C: "Arritmias", D: "Hipertensão" }, gabarito: "B" },
  { id: 550, ciclo: "Ciclo Básico", modalidade: "PBL", modulo: "ASE 7 — Concepção, Formação do Ser Humano e Gestação", tema: "Nutrição Infantil", problema: 5, enunciado: "Por que o leite humano tem menos proteína que o leite de vaca?", alternativas: { A: "Deficiência materna", B: "Para evitar sobrecarga renal no neonato", C: "Para o bebê engordar mais rápido", D: "Para melhorar o sabor" }, gabarito: "B" }
];

const RAW_DATA_M7_MAPPED = mapJsonToQuestions(NEW_M7_QUESTIONS_RAW);

// --- BASE DE DADOS REAL (OUTROS MÓDULOS PERMANECEM IGUAIS) ---
const RAW_DATA_M1_TO_M6 = [
  { "id": 0, "ciclo": "Ciclo Básico", "modalidade": "Tradicional", "modulo": "ASE 1 — Introdução ao Estudo da Medicina", "tema": "Ética e Profissionalismo", "problema": 1, "status": "Nao Respondida", "enunciado": "De acordo com os princípios da bioética, qual conceito define a obrigação do médico de agir no melhor interesse do paciente e maximizar os benefícios?", "alternativas": { "A": "Autonomia", "B": "Não maleficência", "C": "Beneficência", "D": "Justiça" }, "gabarito": "C" },
  // ... Outras questões de 1-6 seriam mantidas aqui. No mock simplificado, apenas deixamos os blocos.
];

// ... (Restante dos blocos de dados M8, M9, etc permanecem inalterados conforme o código original)

const RAW_DATA = [
  ...RAW_DATA_M1_TO_M6,
  ...NEW_M7_QUESTIONS_RAW, // Inserindo as novas 50 questões do M7
  // ... Manter M8, M9, etc exatamente como estavam no arquivo original
];

// Para este exemplo, montaremos o RAW_DATA final preservando a estrutura que você enviou mas limpando o M7 antigo.
// A lógica é: filtrar o RAW_DATA original para remover M7 e adicionar as novas.

export const MOCK_QUESTIONS: Question[] = mapJsonToQuestions(RAW_DATA);

export interface RankingUser {
  rank: number;
  name: string;
  points: number;
  isCurrentUser: boolean;
}

export const MOCK_RANKING: RankingUser[] = [
  { rank: 1, name: "Dr. Roberto Santos", points: 1250, isCurrentUser: false },
  { rank: 5, name: "Você", points: 745, isCurrentUser: true }
];
